import {
  AtSignIcon,
  CalendarIcon,
  ChevronsUpDownIcon,
  CircleDotIcon,
  HashIcon,
  SlidersHorizontalIcon,
  SquareCheckIcon,
  TextIcon,
  ToggleLeftIcon,
  TypeIcon,
  UploadIcon,
} from "lucide-react"

import { FieldType, type FormField } from "../types/field"

export const fields: FormField[] = [
  {
    type: FieldType.INPUT,
    name: "Input",
    label: "Username",
    placeholder: "shadcn",
    description: "Single line text entry",
    Icon: TypeIcon,
    registryDependencies: ["input"],
  },
  {
    type: FieldType.TEXTAREA,
    name: "Textarea",
    label: "Bio",
    placeholder: "Tell us a little bit about yourself",
    description: "Multi-line text entry",
    Icon: TextIcon,
    registryDependencies: ["textarea"],
  },
  {
    type: FieldType.NUMBER_INPUT,
    name: "Number Input",
    label: "Age",
    placeholder: "24",
    description: "Numeric value entry",
    Icon: HashIcon,
    registryDependencies: ["input"],
  },
  {
    type: FieldType.EMAIL,
    name: "Email",
    label: "Email",
    placeholder: "m@example.com",
    description: "Email address entry",
    Icon: AtSignIcon,
    registryDependencies: ["input"],
  },
  {
    type: FieldType.CHECKBOX,
    name: "Checkbox",
    label: "Use different settings for my mobile devices",
    description: "Boolean yes/no toggle",
    Icon: SquareCheckIcon,
    registryDependencies: ["checkbox"],
  },
  {
    type: FieldType.SELECT,
    name: "Select",
    label: "Email",
    placeholder: "Select a verified email to display",
    description: "Dropdown selection",
    Icon: ChevronsUpDownIcon,
    choices: [
      {
        value: "m@example.com",
        label: "m@example.com",
      },
      {
        value: "m@google.com",
        label: "m@google.com",
      },
      {
        value: "m@support.com",
        label: "m@support.com",
      },
    ],
    registryDependencies: ["select"],
  },
  {
    type: FieldType.DATE,
    name: "Date",
    label: "Date of birth",
    description: "Date picker calendar",
    Icon: CalendarIcon,
    registryDependencies: ["popover", "calendar"],
  },
  {
    type: FieldType.RADIO_GROUP,
    name: "Radio Group",
    label: "Notify me about...",
    description: "Single choice from list",
    Icon: CircleDotIcon,
    choices: [
      {
        value: "all",
        label: "All new messages",
      },
      {
        value: "mentions",
        label: "Direct messages and mentions",
      },
      {
        value: "none",
        label: "Nothing",
      },
    ],
    registryDependencies: ["radio-group"],
  },
  {
    type: FieldType.SWITCH,
    name: "Switch",
    label: "Marketing emails",
    description: "On/off toggle control",
    Icon: ToggleLeftIcon,
    registryDependencies: ["switch"],
  },
  {
    type: FieldType.COMBOBOX,
    name: "Combobox",
    label: "Language",
    Icon: ChevronsUpDownIcon,
    description: "Searchable dropdown",
    choices: [
      { label: "English", value: "en" },
      { label: "French", value: "fr" },
      { label: "German", value: "de" },
      { label: "Spanish", value: "es" },
      { label: "Portuguese", value: "pt" },
      { label: "Russian", value: "ru" },
      { label: "Japanese", value: "ja" },
      { label: "Korean", value: "ko" },
      { label: "Chinese", value: "zh" },
    ],
    registryDependencies: ["popover", "command"],
  },
  {
    type: FieldType.SLIDER,
    name: "Slider",
    label: "Slider",
    description: "Range value selector",
    Icon: SlidersHorizontalIcon,
    min: 0,
    max: 100,
    step: 10,
    default: 50,
    registryDependencies: ["slider"],
  },
  {
    type: FieldType.FILE_UPLOAD,
    name: "File Upload",
    label: "Upload File",
    description: "File attachment field",
    Icon: UploadIcon,
    accept: "*/*",
    maxSize: 5,
    multiple: false,
    registryDependencies: ["input"],
  },
]
